language: go
sudo: false
matrix:
  include:
    # "1.x" always refers to the latest Go version, inc. the patch release.
    # e.g. "1.x" is 1.11 until 1.11.1 is available.
    - go: 1.x
      env: GO111MODULE=on

before_install:
  # gox simplifies building for multiple architectures
  - go get github.com/mitchellh/gox

install:
  - # skip

script:
  - go get -t -v ./...
  - export VERSION=$(git describe --tags)
  - gox -os="linux darwin" -arch="amd64" -output="postgres_exporter_${VERSION}_{{.OS}}_{{.Arch}}" -verbose ./...

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: u9gxHcKiSElyVfnRVKM+h8fI6AT6JXg7Z1gqv2t1TZfPzOo/GrNAXv/lKGPEmVx0pq54izik2+z3uOAAD3jiT8KeC7MU/NxNRQvvnPPgmQrLhU/FPViygPVbG9a9u1tEqKp4VGBYLYeGr0uSyXn+kV3t3Ly0EOdx6ppLVp5XUezE3lJDX2t3HZ0O/fK8rRqu17HJP9trlsgxaEIJb8xvG0vlQ5pTGrssK2qZtEj0XGTqlxBpXL0zPOx+KsIFuz39HLUE6J/IGSGUOyKxJzSv+rPFV+/hLMljCdM+vmJ/olfK2fLTBa1+ZopGS9r1yevsi4+B3+GPClUTM4nqB1YR7FxpWG8K9wMawZQhgHafiPMULyn8CZThV69U+Fpj/jrsaS+hvJqJD6j6jQymsF6NuJWSNZCscySERumAVTFpUhlUmnWQv3FdZ0XVrHO1tXx31ue8dU8JL0eLPEbh1Y/djdPJhD21m6BFp2o4rpb9BT1VrPjevDKSNx9FnUHypfQxmK4gvfA+O0GK++3BfshnRYI0ZwwLwzz9lQIlswdYTuOyOIkjC+2hkUG62P/e7O0qapBjeYgsBAi2N1OJ7dnzP1dGgCVyPXGaveI0KtHpYQpUgCAs4eC/AJwws+io2rzUPVBRTJ1g05e2hRPwDwx1ZT5AFFOeC0r6RO2Xl5JC1Os=
  file_glob: true
  file:
    # The names of the binaries to output, based on the -output template passed to gox.
    - "postgres_exporter_${VERSION}_darwin_amd64"
    - "postgres_exporter_${VERSION}_linux_amd64"
  on:
    # What to repository to build
    repo: gojuno/postgres_exporter
    # Only build binaries for tagged commits
    tags: true